//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcInternetApplication.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дом.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрированый пользователь.
        /// </summary>
        public static string UserPaid {
            get {
                return ResourceManager.GetString("UserPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string Администратор {
            get {
                return ResourceManager.GetString("Администратор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актеры.
        /// </summary>
        public static string Актеры {
            get {
                return ResourceManager.GetString("Актеры", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А что по короче имечка нету?.
        /// </summary>
        public static string АЧтоПокорочеИмечкаНету {
            get {
                return ResourceManager.GetString("АЧтоПокорочеИмечкаНету", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А что эту строчку заполнять не нужно?.
        /// </summary>
        public static string АЭтуСтрочечкуЗаполнятьНеНужно {
            get {
                return ResourceManager.GetString("АЭтуСтрочечкуЗаполнятьНеНужно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бедняга не проскочил? Давай еще поугадывай..
        /// </summary>
        public static string БеднягаНеПроскочилДавайЕщеПоугадывай {
            get {
                return ResourceManager.GetString("БеднягаНеПроскочилДавайЕщеПоугадывай", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин и пароль.
        /// </summary>
        public static string ВведитеЛогинИПароль {
            get {
                return ResourceManager.GetString("ВведитеЛогинИПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите старый пароль.
        /// </summary>
        public static string ВведитеСтарыйПароль {
            get {
                return ResourceManager.GetString("ВведитеСтарыйПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Вход {
            get {
                return ResourceManager.GetString("Вход", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы вошли как.
        /// </summary>
        public static string ВыВошлиКак {
            get {
                return ResourceManager.GetString("ВыВошлиКак", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выкупить.
        /// </summary>
        public static string Выкупить {
            get {
                return ResourceManager.GetString("Выкупить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да, Выкупить.
        /// </summary>
        public static string ДаВыкупить {
            get {
                return ResourceManager.GetString("ДаВыкупить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string Дата {
            get {
                return ResourceManager.GetString("Дата", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Добавить {
            get {
                return ResourceManager.GetString("Добавить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление.
        /// </summary>
        public static string Добавление {
            get {
                return ResourceManager.GetString("Добавление", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать.
        /// </summary>
        public static string ДоброПожаловать {
            get {
                return ResourceManager.GetString("ДоброПожаловать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;-Если нет аккаунта.
        /// </summary>
        public static string ЕслиНетАккаунта {
            get {
                return ResourceManager.GetString("ЕслиНетАккаунта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забронировать.
        /// </summary>
        public static string Забронировать {
            get {
                return ResourceManager.GetString("Забронировать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечательная пьеса без актеров, зато ни кто не надоест.
        /// </summary>
        public static string ЗамечательнаяПьесаБезАктеровЗаТоНиКтоНеНадоест {
            get {
                return ResourceManager.GetString("ЗамечательнаяПьесаБезАктеровЗаТоНиКтоНеНадоест", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня.
        /// </summary>
        public static string ЗапомнитьМеня {
            get {
                return ResourceManager.GetString("ЗапомнитьМеня", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить пароль.
        /// </summary>
        public static string ИзменитьПароль {
            get {
                return ResourceManager.GetString("ИзменитьПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Имя {
            get {
                return ResourceManager.GetString("Имя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Контакты {
            get {
                return ResourceManager.GetString("Контакты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курьер.
        /// </summary>
        public static string Курьер {
            get {
                return ResourceManager.GetString("Курьер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личный кабинет.
        /// </summary>
        public static string ЛичныйКабинет {
            get {
                return ResourceManager.GetString("ЛичныйКабинет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Назад {
            get {
                return ResourceManager.GetString("Назад", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название пьесы.
        /// </summary>
        public static string НазваниеПьесы {
            get {
                return ResourceManager.GetString("НазваниеПьесы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не, лучше пивка попью.
        /// </summary>
        public static string НеЛучшеПивкаПопью {
            get {
                return ResourceManager.GetString("НеЛучшеПивкаПопью", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не ну хоть намекни о чем сей шедевр.
        /// </summary>
        public static string НеНуЛюдиДолжныЗнатьОЧемРечь {
            get {
                return ResourceManager.GetString("НеНуЛюдиДолжныЗнатьОЧемРечь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не оплачено.
        /// </summary>
        public static string НеОплачено {
            get {
                return ResourceManager.GetString("НеОплачено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль.
        /// </summary>
        public static string НовыйПароль {
            get {
                return ResourceManager.GetString("НовыйПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер места.
        /// </summary>
        public static string НомерМеста {
            get {
                return ResourceManager.GetString("НомерМеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну и куда это писать? Сократи название.
        /// </summary>
        public static string НуИКудаЭтоПисатьСократиНазвание {
            get {
                return ResourceManager.GetString("НуИКудаЭтоПисатьСократиНазвание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Область зала.
        /// </summary>
        public static string ОбластьЗала {
            get {
                return ResourceManager.GetString("ОбластьЗала", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Она сама себя снимает?.
        /// </summary>
        public static string ОнаСамаСебяСнимает {
            get {
                return ResourceManager.GetString("ОнаСамаСебяСнимает", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Описание {
            get {
                return ResourceManager.GetString("Описание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплачено.
        /// </summary>
        public static string Оплачено {
            get {
                return ResourceManager.GetString("Оплачено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка ввода пароля.
        /// </summary>
        public static string ОшибкаВводаПароля {
            get {
                return ResourceManager.GetString("ОшибкаВводаПароля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель администратора.
        /// </summary>
        public static string ПанельАдминистратора {
            get {
                return ResourceManager.GetString("ПанельАдминистратора", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают.
        /// </summary>
        public static string ПаролиНеСовпадают {
            get {
                return ResourceManager.GetString("ПаролиНеСовпадают", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Пароль {
            get {
                return ResourceManager.GetString("Пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повтоите пароль.
        /// </summary>
        public static string ПовторитеПароль {
            get {
                return ResourceManager.GetString("ПовторитеПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробно.
        /// </summary>
        public static string Подробно {
            get {
                return ResourceManager.GetString("Подробно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть зарегистрированых пользователей.
        /// </summary>
        public static string ПосмотретьЗарегистрированыхПользователей {
            get {
                return ResourceManager.GetString("ПосмотретьЗарегистрированыхПользователей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть свободные места.
        /// </summary>
        public static string ПосмотретьСвободныеМеста {
            get {
                return ResourceManager.GetString("ПосмотретьСвободныеМеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть список пьес.
        /// </summary>
        public static string ПосмотретьСписокПьес {
            get {
                return ResourceManager.GetString("ПосмотретьСписокПьес", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string Применить {
            get {
                return ResourceManager.GetString("Применить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжительность.
        /// </summary>
        public static string Продолжительность {
            get {
                return ResourceManager.GetString("Продолжительность", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Регистрация {
            get {
                return ResourceManager.GetString("Регистрация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование.
        /// </summary>
        public static string Редактирование {
            get {
                return ResourceManager.GetString("Редактирование", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Редактировать {
            get {
                return ResourceManager.GetString("Редактировать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режиссер.
        /// </summary>
        public static string Режиссер {
            get {
                return ResourceManager.GetString("Режиссер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат оплаты.
        /// </summary>
        public static string РезультатОплаты {
            get {
                return ResourceManager.GetString("РезультатОплаты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курьер.
        /// </summary>
        public static string Сourier {
            get {
                return ResourceManager.GetString("Сourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свободные местечки.
        /// </summary>
        public static string СвободныеМеста {
            get {
                return ResourceManager.GetString("СвободныеМеста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string СменаПароля {
            get {
                return ResourceManager.GetString("СменаПароля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового аккаунта.
        /// </summary>
        public static string СозданиеНовогоАккаунта {
            get {
                return ResourceManager.GetString("СозданиеНовогоАккаунта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новую пьесу.
        /// </summary>
        public static string СоздатьНовуюПьесу {
            get {
                return ResourceManager.GetString("СоздатьНовуюПьесу", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новые места в зале.
        /// </summary>
        public static string СоздатьНовыеМестаВЗале {
            get {
                return ResourceManager.GetString("СоздатьНовыеМестаВЗале", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Сохранить {
            get {
                return ResourceManager.GetString("Сохранить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список покупателей.
        /// </summary>
        public static string СписокПокупателей {
            get {
                return ResourceManager.GetString("СписокПокупателей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стартовая.
        /// </summary>
        public static string Стартовая {
            get {
                return ResourceManager.GetString("Стартовая", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница подтверждения заказа.
        /// </summary>
        public static string СтраницаПодтвержденияЗаказа {
            get {
                return ResourceManager.GetString("СтраницаПодтвержденияЗаказа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Театр.
        /// </summary>
        public static string Театр {
            get {
                return ResourceManager.GetString("Театр", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я так понимаю она ни когда не закончится?.
        /// </summary>
        public static string ТоестьОнаНиКогдаНеЗакончится {
            get {
                return ResourceManager.GetString("ТоестьОнаНиКогдаНеЗакончится", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Точно удалить??.
        /// </summary>
        public static string ТочноУдалить {
            get {
                return ResourceManager.GetString("ТочноУдалить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты не поверишь но и это поле желательно заполнить.
        /// </summary>
        public static string ТыНеПоверишьНоИЭтоПолеЖелательноЗаполнить {
            get {
                return ResourceManager.GetString("ТыНеПоверишьНоИЭтоПолеЖелательноЗаполнить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты так всю пьесу расскажешь. По короче нужно.
        /// </summary>
        public static string ТыТакВсюПьесуРасскажешьКорочеНужно {
            get {
                return ResourceManager.GetString("ТыТакВсюПьесуРасскажешьКорочеНужно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты хорошо подумал?.
        /// </summary>
        public static string ТыХорошоПодумал {
            get {
                return ResourceManager.GetString("ТыХорошоПодумал", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас нет забронированых билетов.
        /// </summary>
        public static string УВасНетЗабронированыхБилетов {
            get {
                return ResourceManager.GetString("УВасНетЗабронированыхБилетов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        public static string Удаление {
            get {
                return ResourceManager.GetString("Удаление", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Удалить {
            get {
                return ResourceManager.GetString("Удалить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма для авторизации.
        /// </summary>
        public static string ФормаДляАвторизации {
            get {
                return ResourceManager.GetString("ФормаДляАвторизации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма для регистрации.
        /// </summary>
        public static string ФормаДляРегистрации {
            get {
                return ResourceManager.GetString("ФормаДляРегистрации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма для смены пароля.
        /// </summary>
        public static string ФормаДляСменыПароля {
            get {
                return ResourceManager.GetString("ФормаДляСменыПароля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Цена {
            get {
                return ResourceManager.GetString("Цена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Язык {
            get {
                return ResourceManager.GetString("Язык", resourceCulture);
            }
        }
    }
}
